name: textf_benchmark
description: A new Flutter project to showcase Textf library with flex_color_scheme
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flex_color_scheme: ^8.2.0
  flutter:
    sdk: flutter
  textf: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

