name: textf
description: >
  Markdown-like text styling for inline text — fully compatible with Flutter’s `Text` widget.
  Easily replace Text with Textf to add simple formatting.
version: 1.1.1
homepage: https://github.com/PhilippHGerber/textf
repository: https://github.com/PhilippHGerber/textf
issue_tracker: https://github.com/PhilippHGerber/textf/issues

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0

topics:
  - text
  - widgets
  - markdown
  - formatting

screenshots:
  - description: "Textf Logo"
    path: pub/textf.webp
  - description: "Basic Formatting"
    path: pub/textf_basic.webp
  - description: "Superscript & Subscript"
    path: pub/textf_script.webp
  - description: "Textf Links"
    path: pub/textf_links.webp
  - description: "Placeholders"
    path: pub/textf_placeholders.webp
